### ISSUE TITLE
loading forever on mac

### ISSUE THREAD

**Issue by flckv** [aws-samples/amazon-sumerian-hosts#184]
Uncaught (in promise) CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
    at constructor.extractError (json.js:52:27)
    at constructor.callListeners (sequential_executor.js:106:20)
    at constructor.emit (sequential_executor.js:78:10)
    at constructor.emitEvent (request.js:686:14)
    at constructor.e (request.js:22:10)
    at t.runTo (state_machine.js:14:12)
    at state_machine.js:26:10
    at constructor.<anonymous> (request.js:38:9)
    at constructor.<anonymous> (request.js:688:12)
    at constructor.callListeners (sequential_executor.js:116:18)

**Comment by trusktr** [comment]
Looks like you didn't put credentials config in your env, as the error says. The app will not work without setting authentication keys. You need to log into AWS, and make keys.

**Comment by trusktr** [comment]
@flckv still need help? 

I've updated the lib to vanilla JavaScript modules, and will be improving it more over in this fork (unless maintainers here get active again):

https://github.com/autonomys/amazon-sumerian-hosts

A 3D experience made with it is in progress at https://github.com/autonomys/unnamed-experiment (no name, for now, until we have something to show and announce :)

**Comment by flckv** [comment]
yes indeed, thank you.
